variables:
  colors:
    primaryColor1: C5783A
    primaryColor2: 8E5A79
    primaryColor3: CCCCCC
    primaryColor4: 1A1A1A
    primaryColor5: 9A9A9A
    mainMenuBgColor: E6D19A
    mainMenuFontColor: 1A1A1A
    mainMenuBorderColor: 1A1A1A
    buttonBgColor: 9A9A9A
    buttonFontColor: 1A1A1A
    buttonBorderColor: 1A1A1A
  fonts:
    defaultHeaderFont: georgia
    defaultBodyFont: helvetica
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://images.png'
favicon:
  use_default: false
  path: 'public://Iconka-Saint-Whiskers-Cat-food-hearts.ico'
  mimetype: image/vnd.microsoft.icon
omega_toggle_intro: 1
enable_backups: 0
force_subtheme_creation: 0
block_demo_mode: 0
screen_demo_indicator: 0
default_layout: primary
home_layout: primary
enable_omegags_layout: 1
layouts: {  }
breakpoint_group_primary: subthemeomega.default
node_type_article_layout: primary
node_type_page_layout: primary
taxonomy_category_layout: primary
taxonomy_tags_layout: primary
edit_this_layout: primary
_core:
  default_config_hash: 2lLiWKrBx6pe-gkL-vR2WLMHOwzfkIlnSCbp7OkvT_I
compile_scss: 1
show_compile_warning: 1
enable_omega_badge: 1
styles:
  subthemeomega/subthemeomega: 1
  omega/omega: 1
  omega/omega_html_elements: 1
  omega/omega_branding: 1
  omega/omega_breadcrumbs: 1
  omega/omega_main_menus: 1
  omega/omega_messages: 1
  omega/omega_pagers: 1
  omega/omega_tabs: 1
  omega/omega_taxonomy_terms: 1
  omega/omega_forms: 1
  omega_simple_starterkit/omega_simple_starterkit: 1
